version: "3.8"

services:
  service-utils-nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 8082:80
    depends_on:
      - utils-php-fpm

  utils-php-fpm:
    image: maxrollundev/php-fpm-dev-8.0
    volumes:
      - ./:/var/www/app
    environment:
      PHP_IDE_CONFIG: "serverName=php-fpm"
      DB_DRIVER: Pdo_Mysql
      DB_USER: utils_db
      DB_NAME: utils_db
      DB_HOST: mysql
      DB_PASS: secret
      DB_PORT: 3306
      TRACK_PROCESSES: 'true'

  mysql:
    image: mysql:8.2
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: utils_db
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: utils_db
    ports:
      - 33061:3306

volumes:
  mysql: